// PIKT: Generates offline Iconify (Material Symbols) data for the UI chrome icons used via MdIcon.
// Bundles ONLY the icons the app actually uses (no Iconify API at runtime, app is fully offline).
// Re-run with `node scripts/gen-icons.mjs`. If it reports MISSING names, add an entry to OVERRIDES.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const collection = require("@iconify-json/material-symbols/icons.json");
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/styles/icon_data.ts");

// "" = filled base style (all names exist); set to "-outline" for outlined look (verify variants first).
const STYLE = "";

// material-icons names (underscore) used as UI chrome (MdIcon). sv-check enforces this stays complete.
const CHROME = [
  // PIKT navigation/shell + editor icons (Chantier 0/2)
  "home", "dashboard", "photo_library", "bolt", "add_photo_alternate", "style", "inventory_2", "aspect_ratio",
  "123", "abc", "add", "arrow_downward", "auto_fix_high",
  "battery_0_bar", "battery_2_bar", "battery_3_bar", "battery_5_bar", "battery_full",
  "bluetooth", "bug_report", "calendar_today", "cancel_presentation", "chevron_left",
  "chevron_right", "close", "code", "content_copy", "control_camera", "crop_square",
  "data_object", "dataset", "delete", "density_medium", "download", "edit", "edit_note",
  "emoji_emotions", "expand", "expand_more", "fit_screen", "folder", "format_align_center",
  "format_align_left", "format_align_right", "format_bold", "format_color_fill",
  "format_color_text", "format_italic", "format_shapes", "format_size", "grid_on",
  "horizontal_distribute", "hourglass_top", "image", "invert_colors", "line_weight",
  "lock", "lock_open", "picture_as_pdf", "power", "power_off", "print", "qr_code_2",
  "radio_button_unchecked", "receipt_long", "redo", "refresh", "remove", "rounded_corner",
  "save", "schedule", "sd_storage", "segment", "sentiment_very_dissatisfied", "settings",
  "settings_ethernet", "swap_horiz", "tag", "text_decrease", "text_format", "text_increase",
  "title", "undo", "unfold_more", "usb", "vertical_align_bottom", "vertical_align_center",
  "vertical_align_top", "vertical_distribute", "view_week", "visibility", "warning", "wrap_text",
];

// material-icons name -> material-symbols (hyphenated) name, for names that are missing or differ.
const OVERRIDES = {
  sd_storage: "sd-card",
  emoji_emotions: "mood",
};

const icons = collection.icons || {};
const aliases = collection.aliases || {};

function resolveIcon(symName) {
  let name = symName;
  const t = {};
  let guard = 0;
  while (aliases[name] && !icons[name] && guard++ < 8) {
    const a = aliases[name];
    if (a.hFlip) t.hFlip = !t.hFlip;
    if (a.vFlip) t.vFlip = !t.vFlip;
    if (a.rotate) t.rotate = ((t.rotate || 0) + a.rotate) % 4;
    name = a.parent;
  }
  const ic = icons[name];
  if (!ic) return null;
  const data = {
    body: ic.body,
    width: ic.width || collection.width || 24,
    height: ic.height || collection.height || 24,
  };
  if (t.hFlip) data.hFlip = true;
  if (t.vFlip) data.vFlip = true;
  if (t.rotate) data.rotate = t.rotate;
  return data;
}

const out = {};
const missing = [];
for (const mi of CHROME) {
  const sym = (OVERRIDES[mi] ?? mi.replace(/_/g, "-")) + STYLE;
  const data = resolveIcon(sym);
  if (!data) {
    missing.push(`${mi} -> ${sym}`);
    continue;
  }
  out[mi] = data;
}

if (missing.length) {
  console.error("MISSING (add to OVERRIDES in gen-icons.mjs):\n" + missing.join("\n"));
  process.exit(1);
}

const keys = Object.keys(out).sort();
const entries = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(out[k])},`).join("\n");
const ts = `// PIKT: GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Offline Iconify (Material Symbols) data for UI chrome icons. Run \`node scripts/gen-icons.mjs\`.
import type { IconifyIcon } from "@iconify/types";

export const ICON_DATA = {
${entries}
} satisfies Record<string, IconifyIcon>;

export type IconName = keyof typeof ICON_DATA;
`;
writeFileSync(OUT, ts);
console.log(`Wrote ${OUT} (${keys.length} icons)`);
