// PIKT: Generates the Skeleton v4 custom theme `niimbotator` from the brand colors
// defined in docs/UX-GUIDELINES.md (§2.4). Ramps are computed in OKLCH for
// perceptual uniformity. Re-run with `node scripts/gen-theme.mjs` if brand colors change.
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/themes/niimbotator.css");

// --- Brand 500-level colors (UX-GUIDELINES §2.4) ---
const BRAND = {
  primary: "#1976D2", // blue
  secondary: "#5E35B1", // violet
  tertiary: "#00897B", // teal
  success: "#388E3C", // green
  warning: "#F57C00", // orange
  error: "#D32F2F", // red
};

// --- sRGB hex -> OKLCH (Björn Ottosson) ---
const hexToRgb = (hex) => {
  const h = hex.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
};
const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));
const linearToOklab = (r, g, b) => {
  const l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b;
  const m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b;
  const s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b;
  const l_ = Math.cbrt(l), m_ = Math.cbrt(m), s_ = Math.cbrt(s);
  return [
    0.2104542553 * l_ + 0.793617785 * m_ - 0.0040720468 * s_,
    1.9779984951 * l_ - 2.428592205 * m_ + 0.4505937099 * s_,
    0.0259040371 * l_ + 0.7827717662 * m_ - 0.808675766 * s_,
  ];
};
const hexToOklch = (hex) => {
  const [r, g, b] = hexToRgb(hex).map(srgbToLinear);
  const [L, a, bb] = linearToOklab(r, g, b);
  const C = Math.hypot(a, bb);
  let H = (Math.atan2(bb, a) * 180) / Math.PI;
  if (H < 0) H += 360;
  return [L, C, H];
};

// --- Ramp shape (lightness descent + relative-chroma bell, mirrors Skeleton presets) ---
const STOPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
const L_SCALE = [0.96, 0.9, 0.82, 0.74, 0.65, 0.58, 0.52, 0.46, 0.4, 0.34, 0.28];
const C_CURVE = [0.32, 0.5, 0.7, 0.86, 0.96, 1.0, 0.96, 0.88, 0.78, 0.66, 0.55];
const CONTRAST_DARK_MAX_L = 0.62; // stops lighter than this take dark text

const fmt = (n) => +n.toFixed(3);

function rampCss(role, hex) {
  const [, C, H] = hexToOklch(hex);
  const lines = [];
  STOPS.forEach((stop, i) => {
    lines.push(`\t--color-${role}-${stop}: oklch(${fmt(L_SCALE[i])} ${fmt(C * C_CURVE[i])} ${fmt(H)});`);
  });
  lines.push(`\t--color-${role}-contrast-dark: var(--color-${role}-950);`);
  lines.push(`\t--color-${role}-contrast-light: var(--color-${role}-50);`);
  STOPS.forEach((stop, i) => {
    const which = L_SCALE[i] >= CONTRAST_DARK_MAX_L ? "dark" : "light";
    lines.push(`\t--color-${role}-contrast-${stop}: var(--color-${role}-contrast-${which});`);
  });
  return lines.join("\n");
}

// Neutral surface ramp (achromatic)
function surfaceCss() {
  const lines = [];
  STOPS.forEach((stop, i) => {
    lines.push(`\t--color-surface-${stop}: oklch(${fmt(L_SCALE[i] === 0.96 ? 0.99 : L_SCALE[i])} 0 0);`);
  });
  lines.push(`\t--color-surface-contrast-dark: var(--color-surface-950);`);
  lines.push(`\t--color-surface-contrast-light: var(--color-surface-50);`);
  STOPS.forEach((stop, i) => {
    const which = L_SCALE[i] >= CONTRAST_DARK_MAX_L ? "dark" : "light";
    lines.push(`\t--color-surface-contrast-${stop}: var(--color-surface-contrast-${which});`);
  });
  return lines.join("\n");
}

const header = `/* PIKT: GENERATED by scripts/gen-theme.mjs — do not edit by hand. */
/* Niimbotator Skeleton v4 theme. Brand colors per docs/UX-GUIDELINES.md §2.4, ramps in OKLCH. */
[data-theme='niimbotator'] {
\t--spacing: 0.25rem;
\t--text-scaling: 1.067;
\t--base-font-color: var(--color-surface-950);
\t--base-font-color-dark: var(--color-surface-50);
\t--base-font-family: "Noto Sans Variable", system-ui, sans-serif;
\t--base-font-size: inherit;
\t--base-line-height: inherit;
\t--base-font-weight: normal;
\t--base-font-style: normal;
\t--base-letter-spacing: 0em;
\t--heading-font-color: inherit;
\t--heading-font-color-dark: inherit;
\t--heading-font-family: inherit;
\t--heading-font-weight: 600;
\t--heading-font-style: normal;
\t--heading-letter-spacing: inherit;
\t--anchor-font-color: var(--color-primary-600);
\t--anchor-font-color-dark: var(--color-primary-400);
\t--anchor-font-family: inherit;
\t--anchor-font-size: inherit;
\t--anchor-line-height: inherit;
\t--anchor-font-weight: inherit;
\t--anchor-font-style: inherit;
\t--anchor-letter-spacing: inherit;
\t--anchor-text-decoration: none;
\t--anchor-text-decoration-hover: underline;
\t--anchor-text-decoration-active: none;
\t--anchor-text-decoration-focus: none;
\t--body-background-color: var(--color-surface-50);
\t--body-background-color-dark: var(--color-surface-950);
\t--radius-base: 0.5rem;
\t--radius-container: 0.75rem;
\t--default-border-width: 1px;
\t--default-divide-width: 1px;
\t--default-ring-width: 1px;`;

const body = [
  rampCss("primary", BRAND.primary),
  rampCss("secondary", BRAND.secondary),
  rampCss("tertiary", BRAND.tertiary),
  rampCss("success", BRAND.success),
  rampCss("warning", BRAND.warning),
  rampCss("error", BRAND.error),
  surfaceCss(),
].join("\n");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, `${header}\n${body}\n}\n`);
console.log(`Wrote ${OUT}`);
